version: "3.9"
services:
  spark:
    build: .
    container_name: spark-container
    environment:
      - SPARK_HOME=/opt/spark
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["python", "main.py", "stream"]
