version: "3.9"
services:
  spark:
    build: .
    container_name: spark-container
    environment:
      - PROCESSING=${PROCESSING}
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["python", "main.py", "${PROCESSING}"]
